version: "3"

services:
  redis:
    container_name: redisCache
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - net101

  redisinsight:
    container_name: redisInsight
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db
    networks:
      - net101

networks:
  net101:
    external: true
    name: net101

volumes:
  redis:
    driver: local
  redisinsight:
    driver: local