name: smart-heart-invoice-service-production

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: [self-hosted, smart-heart-invoice-service-production]
    env:
      NODE_ENV: ${{secrets.PROD_NODE_ENV}}
      PORT: ${{secrets.PROD_PORT}}
      POSTGRES_HOST: ${{secrets.PROD_POSTGRES_HOST}}
      POSTGRES_PORT: ${{secrets.PROD_POSTGRES_PORT}}
      POSTGRES_USER: ${{secrets.PROD_POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.PROD_POSTGRES_PASSWORD}}
      POSTGRES_DATABASE: ${{secrets.PROD_POSTGRES_DATABASE}}
      SYNCHRONIZE: ${{secrets.PROD_SYNCHRONIZE}}
      REDIS_HOST: ${{secrets.PROD_REDIS_HOST}}
      REDIS_PORT: ${{secrets.PROD_REDIS_PORT}}
      PATH_FILE: ${{secrets.PATH_FILE}}
      PATH_TEMPLATE: ${{secrets.PATH_TEMPLATE}}

    steps:
      - uses: actions/checkout@main

      - name: Create .env
        run: |
          touch .env
          echo NODE_ENV=$NODE_ENV >> .env
          echo PORT=$PORT >> .env
          echo POSTGRES_HOST=$POSTGRES_HOST >> .env
          echo POSTGRES_PORT=$POSTGRES_PORT >> .env
          echo POSTGRES_USER=$POSTGRES_USER >> .env
          echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> .env
          echo POSTGRES_DATABASE=$POSTGRES_DATABASE >> .env
          echo SYNCHRONIZE=$SYNCHRONIZE >> .env
          echo REDIS_HOST=$REDIS_HOST >> .env
          echo REDIS_PORT=$REDIS_PORT >> .env

      - name: export PATH_FILE
        run: export PATH_FILE=$PATH_FILE

      - name: export PATH_TEMPLATE
        run: export PATH_TEMPLATE=$PATH_TEMPLATE

      - name: Run docker compose for smart-heart-invoice-service-production
        run: docker compose up -d --build smart-heart-invoice-service-production

      - name: Delete container unused
        run: docker system prune -f

      - name: Delete image unused
        run: docker image prune -f
